# Generated by Django 3.1.7 on 2021-10-14 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('bdr', models.CharField(max_length=3)),
                ('sqmeters', models.CharField(max_length=100)),
                ('rent', models.CharField(max_length=100)),
                ('landlord', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('user_notified', models.DateField(blank=True, null=True)),
                ('search_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.searchurl')),
            ],
        ),
    ]
