# Generated by Django 2.2.7 on 2023-10-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_id", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(max_length=200)),
                ("bdr", models.CharField(max_length=3)),
                ("sqmeters", models.CharField(max_length=100)),
                ("rent", models.CharField(max_length=100)),
                ("landlord", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("emailed", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
